### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by DogiFnf** [vo0ov/PyroArgs#1]
Обновите примеры.

**Comment by vo0ov** [comment]
Хорошо. Будет добавлено в следующей версии.

**Comment by DogiFnf** [comment]
> Хорошо. Будет добавлено в следующей версии.

и не забудьте добавить поддержку юзерботов

**Comment by vo0ov** [comment]
Структура обычных ботов и юзер ботов в Pyrogram полностью совпадает, поэтому поддержка юзер ботов будет доступна всегда.
